### ISSUE TITLE
Detected as a trojan 

### ISSUE THREAD

**Issue by manuelv04** [Maickonn/AllaKore_Remote#10]
Artemis!C75F5E083A9B

**Comment by mathst** [comment]
the solution i found for this was to sign the .exe and install the signature on the pc

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
