### ISSUE TITLE
Interaction with the Log-in screen ?

### ISSUE THREAD

**Issue by YordanYanakiev** [Maickonn/AllaKore_Remote#11]
Hello fellows.
Is there a way to interact with the login screen, since currently if someone lock the PC - i see a white screen only. :|

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
