### ISSUE TITLE
works on windows only ?

### ISSUE THREAD

**Issue by gvsurenderreddy** [Maickonn/AllaKore_Remote#12]

**Comment by gvsurenderreddy** [comment]
hello sir can i use this for linux as well pleawsew

**Comment by mathst** [comment]
this system was designed for windows, it has many functions that only work for windows, so I would have to make a client for linux that works the same way as the one for windows

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
