### ISSUE TITLE
分辨率不一样的屏幕显示不全是怎么修改，还有远程后无法点击切换输入光标

### ISSUE THREAD

**Issue by khsaga110** [Maickonn/AllaKore_Remote#13]

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
