### ISSUE TITLE
The file transfer encounters an error.

### ISSUE THREAD

**Issue by cn17173** [Maickonn/AllaKore_Remote#15]
When transferring files, it gets stuck around 60-70% of the transfer process.

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
