### ISSUE TITLE
Issue resolution kinda poor quality or 256 colors  no option to change it?

### ISSUE THREAD

**Issue by armadix** [Maickonn/AllaKore_Remote#16]
First thing thanks Maickoon for making this project its awesome by the way. Using a simple IdTCPServer and IdTCPClient can show a good quality resolution as the remote desktop but it will slowdown some performance the AllaKore_Remote have a 16bit or say 256 colors performance is good but if only it can be more colors like 24bit colors not 32bit colors so we can see the text clearer on the remote its a bit of pain not seeing those things when you do remote.

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
