### ISSUE TITLE
Can not see remote screen

### ISSUE THREAD

**Issue by FoxPIM** [Maickonn/AllaKore_Remote#4]
I test this source code,all work finally but I can not see remote screen, why? thanks

**Comment by maickonn** [comment]
Hello, could you provide more details, such as operating system version, was the test performed on internal or external network?

**Comment by FoxPIM** [comment]
这么说吧，把里面的压缩功能屏蔽了，就一切正常了。

**Comment by FoxPIM** [comment]
这么说吧，把里面的压缩功能屏蔽了，就一切正常了，只是费流量。
所以我确信问题是出在压缩相关的功能里。
测试平台：Server端Win Server2016，Client端Win10

**Comment by FoxPIM** [comment]
这么说吧，把里面的压缩功能屏蔽了，就一切正常了，只是费流量。
所以我确信问题是出在压缩相关的功能里。
测试平台：Server端Win Server2016，Client端Win10

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
