### ISSUE TITLE
License unknown

### ISSUE THREAD

**Issue by JensMertelmeyer** [Maickonn/AllaKore_Remote#5]
I am unable to find license information about this project. Can you please chose a license for this project, in case you have not decided yet?

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
