### ISSUE TITLE
Não Gerar o ID e Senha

### ISSUE THREAD

**Issue by ClarckDaivson** [Maickonn/AllaKore_Remote#7]
**_Quando projeto fica com status  de conectado mais não gerar o id e senha, 
teria algum coisa que possa tá fazendo._**

**Comment by pedrohanderson2** [comment]
deve verificar a porta e o ip do servidor

**Comment by maickonn** [comment]
Olá, peço desculpas pela demora na resposta. Gostaria de informar que este projeto foi descontinuado e está atualmente em processo de arquivamento. No entanto, há alguns forks altamente promissores que estão avançados e oferecem muitos recursos. Recomendo verificar o [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), um projeto em desenvolvimento ativo pela Comunidade Open Source Brazil.
