### ISSUE TITLE
Cross platform

### ISSUE THREAD

**Issue by gvsurenderreddy** [Maickonn/AllaKore_Remote#8]
Hello does this support cross platform

**Comment by irwanto82** [comment]
is there any lazarus version with indy, specially for server

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
