### ISSUE TITLE
Picture Quality 

### ISSUE THREAD

**Issue by manuelv04** [Maickonn/AllaKore_Remote#9]
Is there a way to increase the resolution or picture quality it seems like I am getting 16bits resolution?

**Comment by maickonn** [comment]
Hello, I apologize for the delayed response. I'd like to inform you that this project has been discontinued and is currently in the process of being archived. However, there are some highly promising forks that are quite advanced and feature-rich. I recommend checking out [Aegys](https://github.com/OpenSourceCommunityBrasil/Aegys-Acesso-Remoto), which is actively developed by the Open Source Community Brazil.
